chore: Relax unique versioning requirements
Update release process so that PR into main only requires a version bump
if the version in the local cargo.toml exists as a tag in the container
registry. This will ensure that the version number is bumped for the next
release while allowing refactor and chore type commits to be merged
without unnecessarily bumping the version.

diff --git a/.github/workflows/enforce-versioning.yaml b/.github/workflows/enforce-versioning.yaml
--- a/.github/workflows/enforce-versioning.yaml
+++ b/.github/workflows/enforce-versioning.yaml
@@ -53,10 +53,18 @@ jobs:
           echo "semver=${VERSION}" >> "${GITHUB_OUTPUT}"
           echo "${VERSION}"
                     
-  enforce-version-increment:
-    name: Check if version must be incremented
-    needs: get-version
+  enforce-unique-tag:
+    name: Enforce Unique Image Tag
     runs-on: ubuntu-latest
+    needs: get-version
+
+    permissions:
+      contents: read
+      packages: write
+      id-token: write
+
+    outputs:
+      skip: ${{ steps.tag-check.outputs.skip }}
 
     steps:
       - name: Checkout Repository
@@ -67,29 +75,39 @@ jobs:
           # Setting fetch depth to zero will fetch all branches.
           fetch-depth: 0
 
-      - name: Check version
-        run: |
-          head_version=${{ needs.get-version.outputs.semver-head }}
-          main_version=${{ needs.get-version.outputs.semver-main }}
+      - name: Log in to the Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Check if tag exists
+        id: tag-check
+        run: |
           ./scripts/check_source_changed.sh -b origin/main || exit_code=$?
-         
+
           if [[ -z $exit_code ]]; then
-            if [[ $head_version == $main_version ]]; then
-              echo "Source has not changed and neither has the version, no action needed 😎👍."
-              exit 0
-            else
-              echo "🚨 🖐️👮 Source has not changed, but the version has changed. Change the version back to $main_version! 🚨" >&2
-              exit 1
-            fi
+            echo "✅ Source code is unchanged, skipping full check."
+            exit 0
           elif [[ $exit_code -eq 1 ]]; then
-            if [[ $head_version == $main_version ]]; then
-              echo "🚨 🖐️👮 Source has changed, but the version has not been updated. Increase the version! 🚨" >&2
-              exit 1
-            else
-              echo "Source has changed and so has the version, no action needed 😎👍"
-              exit 0
-            fi
+            echo "ℹ️ Checking tag is unique."
           else
-            exit $exit_code
+            echo "❗Unexpected exit code $exit_code"
+            exit 1
           fi
+
+          exit_code=""
+          RESULT=$(docker manifest inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.get-version.outputs.semver }} 2>&1 || exit_code=$?)
+
+          if [[ -n $exit_code && $RESULT != "manifest unknown" ]]; then
+            echo "❗Error $exit_code: $RESULT"
+            exit 1
+          fi
+
+          if [ "$RESULT" != "manifest unknown" ]; then
+            echo "🚨 Tag already exists, update the version in Cargo.toml! 🚨"
+            exit 1
+          fi
+
+          echo "✅ Tag is unique"
